name: Create Release
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'The type of release. Must be major, minor or patch'
        required: true
jobs:
  create_release:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      # Make sure we can lint before creating the release.
      - name: Cocoapods lint
        run: make cocoapods
      # Make sure we can build with Carthage before the release
      - name: Build and archive framework for Carthage users
        env:
          DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
        run: ./carthage.sh build --no-skip-current && ./carthage.sh archive
      - name: Create XCFramework
        uses: unsignedapps/swift-create-xcframework@v1.3
        env:
          DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
      - name: Create Release Branch
        env:
          GITHUB_CHANGELOG_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          OSS_PROJECT: PINCache
        run: |
          gem install github_changelog_generator
          Scripts/release.sh --${{ github.event.inputs.release-type }}
          git push origin HEAD
      - name: Tag Release
        run: Scripts/tag-release-branch.sh
      - name: Publish Release
        uses: actions/create-release@v1
        env:
          GITHUB_CHANGELOG_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_TAG }}
          body_path: RELEASE_NOTES.md
          draft: false
      - name: Upload artifacts
        uses: csexton/release-asset-action@v2
        env:
          FRAMEWORK_NAME: "PINCache"
        with:
          files: |
            ${{env.FRAMEWORK_NAME}}.framework.zip
            ${{env.FRAMEWORK_NAME}}.zip
            ${{env.FRAMEWORK_NAME}}.sha256
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
      - name: Push to Cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push

